version: '3.7'
services:
  mysql:
    image: library/mysql:5.7.30
    restart: always
    ports:
      - 3310:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: leboncode
    volumes:
      - admin-leboncode:/var/lib/mysql
volumes:
  admin-leboncode:
